#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esra.ConvertToBpmsRating
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="esra")]
	public partial class DataClassesOldSystemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertalbum_category(album_category instance);
    partial void Updatealbum_category(album_category instance);
    partial void Deletealbum_category(album_category instance);
    partial void Insertalbum(album instance);
    partial void Updatealbum(album instance);
    partial void Deletealbum(album instance);
    partial void Insertalbums_content(albums_content instance);
    partial void Updatealbums_content(albums_content instance);
    partial void Deletealbums_content(albums_content instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertgame_publisher(game_publisher instance);
    partial void Updategame_publisher(game_publisher instance);
    partial void Deletegame_publisher(game_publisher instance);
    partial void Insertgame_version_category(game_version_category instance);
    partial void Updategame_version_category(game_version_category instance);
    partial void Deletegame_version_category(game_version_category instance);
    partial void Insertgames_introduction(games_introduction instance);
    partial void Updategames_introduction(games_introduction instance);
    partial void Deletegames_introduction(games_introduction instance);
    partial void Insertpayamha(payamha instance);
    partial void Updatepayamha(payamha instance);
    partial void Deletepayamha(payamha instance);
    #endregion
		
		public DataClassesOldSystemDataContext() : 
				base(global::Esra.ConvertToBpmsRating.Properties.Settings.Default.esraConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOldSystemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOldSystemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOldSystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOldSystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<age> ages
		{
			get
			{
				return this.GetTable<age>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<album_category> album_categories
		{
			get
			{
				return this.GetTable<album_category>();
			}
		}
		
		public System.Data.Linq.Table<album> albums
		{
			get
			{
				return this.GetTable<album>();
			}
		}
		
		public System.Data.Linq.Table<albums_content> albums_contents
		{
			get
			{
				return this.GetTable<albums_content>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<content> contents
		{
			get
			{
				return this.GetTable<content>();
			}
		}
		
		public System.Data.Linq.Table<game_genre> game_genres
		{
			get
			{
				return this.GetTable<game_genre>();
			}
		}
		
		public System.Data.Linq.Table<game_publisher> game_publishers
		{
			get
			{
				return this.GetTable<game_publisher>();
			}
		}
		
		public System.Data.Linq.Table<game_version_category> game_version_categories
		{
			get
			{
				return this.GetTable<game_version_category>();
			}
		}
		
		public System.Data.Linq.Table<game_version_content> game_version_contents
		{
			get
			{
				return this.GetTable<game_version_content>();
			}
		}
		
		public System.Data.Linq.Table<game_version> game_versions
		{
			get
			{
				return this.GetTable<game_version>();
			}
		}
		
		public System.Data.Linq.Table<game> games
		{
			get
			{
				return this.GetTable<game>();
			}
		}
		
		public System.Data.Linq.Table<games_introduction> games_introductions
		{
			get
			{
				return this.GetTable<games_introduction>();
			}
		}
		
		public System.Data.Linq.Table<games_introduction_genre> games_introduction_genres
		{
			get
			{
				return this.GetTable<games_introduction_genre>();
			}
		}
		
		public System.Data.Linq.Table<games_introduction_platform> games_introduction_platforms
		{
			get
			{
				return this.GetTable<games_introduction_platform>();
			}
		}
		
		public System.Data.Linq.Table<genre> genres
		{
			get
			{
				return this.GetTable<genre>();
			}
		}
		
		public System.Data.Linq.Table<isactive> isactives
		{
			get
			{
				return this.GetTable<isactive>();
			}
		}
		
		public System.Data.Linq.Table<littlenew> littlenews
		{
			get
			{
				return this.GetTable<littlenew>();
			}
		}
		
		public System.Data.Linq.Table<login> logins
		{
			get
			{
				return this.GetTable<login>();
			}
		}
		
		public System.Data.Linq.Table<Module_user> Module_users
		{
			get
			{
				return this.GetTable<Module_user>();
			}
		}
		
		public System.Data.Linq.Table<Module> Modules
		{
			get
			{
				return this.GetTable<Module>();
			}
		}
		
		public System.Data.Linq.Table<payamha> payamhas
		{
			get
			{
				return this.GetTable<payamha>();
			}
		}
		
		public System.Data.Linq.Table<platform> platforms
		{
			get
			{
				return this.GetTable<platform>();
			}
		}
		
		public System.Data.Linq.Table<publisher_user> publisher_users
		{
			get
			{
				return this.GetTable<publisher_user>();
			}
		}
		
		public System.Data.Linq.Table<publisher> publishers
		{
			get
			{
				return this.GetTable<publisher>();
			}
		}
		
		public System.Data.Linq.Table<result> results
		{
			get
			{
				return this.GetTable<result>();
			}
		}
		
		public System.Data.Linq.Table<source> sources
		{
			get
			{
				return this.GetTable<source>();
			}
		}
		
		public System.Data.Linq.Table<sub_genre> sub_genres
		{
			get
			{
				return this.GetTable<sub_genre>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ages")]
	public partial class age
	{
		
		private int _id;
		
		private string _title;
		
		public age()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user
	{
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _system_code;
		
		private string _email;
		
		private string _mobile_number;
		
		private string _u_address;
		
		private string _postal_code;
		
		private string _system_title;
		
		private string _class;
		
		private string _lastvisit;
		
		public user()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this._first_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this._last_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_code", DbType="NVarChar(50)")]
		public string system_code
		{
			get
			{
				return this._system_code;
			}
			set
			{
				if ((this._system_code != value))
				{
					this._system_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_number", DbType="NVarChar(20)")]
		public string mobile_number
		{
			get
			{
				return this._mobile_number;
			}
			set
			{
				if ((this._mobile_number != value))
				{
					this._mobile_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_address", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string u_address
		{
			get
			{
				return this._u_address;
			}
			set
			{
				if ((this._u_address != value))
				{
					this._u_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="NVarChar(20)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this._postal_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_title", DbType="NVarChar(350)")]
		public string system_title
		{
			get
			{
				return this._system_title;
			}
			set
			{
				if ((this._system_title != value))
				{
					this._system_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="NVarChar(50)")]
		public string @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this._class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastvisit", DbType="NVarChar(50)")]
		public string lastvisit
		{
			get
			{
				return this._lastvisit;
			}
			set
			{
				if ((this._lastvisit != value))
				{
					this._lastvisit = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.album_categories")]
	public partial class album_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public album_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.albums")]
	public partial class album : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<int> _category_id;
		
		private string _path;
		
		private System.Nullable<long> _creation_date;
		
		private System.Nullable<long> _last_modified_date;
		
		private bool _isDeleted;
		
		private string _cover;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Oncategory_idChanging(System.Nullable<int> value);
    partial void Oncategory_idChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void Oncreation_dateChanging(System.Nullable<long> value);
    partial void Oncreation_dateChanged();
    partial void Onlast_modified_dateChanging(System.Nullable<long> value);
    partial void Onlast_modified_dateChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    partial void OncoverChanging(string value);
    partial void OncoverChanged();
    #endregion
		
		public album()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(500)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int")]
		public System.Nullable<int> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="NVarChar(200)")]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creation_date", DbType="BigInt")]
		public System.Nullable<long> creation_date
		{
			get
			{
				return this._creation_date;
			}
			set
			{
				if ((this._creation_date != value))
				{
					this.Oncreation_dateChanging(value);
					this.SendPropertyChanging();
					this._creation_date = value;
					this.SendPropertyChanged("creation_date");
					this.Oncreation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_modified_date", DbType="BigInt")]
		public System.Nullable<long> last_modified_date
		{
			get
			{
				return this._last_modified_date;
			}
			set
			{
				if ((this._last_modified_date != value))
				{
					this.Onlast_modified_dateChanging(value);
					this.SendPropertyChanging();
					this._last_modified_date = value;
					this.SendPropertyChanged("last_modified_date");
					this.Onlast_modified_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL")]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cover", DbType="NVarChar(100)")]
		public string cover
		{
			get
			{
				return this._cover;
			}
			set
			{
				if ((this._cover != value))
				{
					this.OncoverChanging(value);
					this.SendPropertyChanging();
					this._cover = value;
					this.SendPropertyChanged("cover");
					this.OncoverChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.albums_contents")]
	public partial class albums_content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _album_id;
		
		private string _file_name;
		
		private string _name;
		
		private string _caption;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onalbum_idChanging(int value);
    partial void Onalbum_idChanged();
    partial void Onfile_nameChanging(string value);
    partial void Onfile_nameChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncaptionChanging(string value);
    partial void OncaptionChanged();
    #endregion
		
		public albums_content()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_id", DbType="Int NOT NULL")]
		public int album_id
		{
			get
			{
				return this._album_id;
			}
			set
			{
				if ((this._album_id != value))
				{
					this.Onalbum_idChanging(value);
					this.SendPropertyChanging();
					this._album_id = value;
					this.SendPropertyChanged("album_id");
					this.Onalbum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string file_name
		{
			get
			{
				return this._file_name;
			}
			set
			{
				if ((this._file_name != value))
				{
					this.Onfile_nameChanging(value);
					this.SendPropertyChanging();
					this._file_name = value;
					this.SendPropertyChanged("file_name");
					this.Onfile_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caption", DbType="NVarChar(200)")]
		public string caption
		{
			get
			{
				return this._caption;
			}
			set
			{
				if ((this._caption != value))
				{
					this.OncaptionChanging(value);
					this.SendPropertyChanging();
					this._caption = value;
					this.SendPropertyChanged("caption");
					this.OncaptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categories")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _titleEn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OntitleEnChanging(string value);
    partial void OntitleEnChanged();
    #endregion
		
		public category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titleEn", DbType="NVarChar(50)")]
		public string titleEn
		{
			get
			{
				return this._titleEn;
			}
			set
			{
				if ((this._titleEn != value))
				{
					this.OntitleEnChanging(value);
					this.SendPropertyChanging();
					this._titleEn = value;
					this.SendPropertyChanged("titleEn");
					this.OntitleEnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.contents")]
	public partial class content
	{
		
		private int _id;
		
		private string _title;
		
		public content()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.game_genres")]
	public partial class game_genre
	{
		
		private int _id;
		
		private System.Nullable<int> _game_id;
		
		private System.Nullable<int> _genre_id;
		
		private System.Nullable<int> _sub_id;
		
		public game_genre()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_id", DbType="Int")]
		public System.Nullable<int> game_id
		{
			get
			{
				return this._game_id;
			}
			set
			{
				if ((this._game_id != value))
				{
					this._game_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre_id", DbType="Int")]
		public System.Nullable<int> genre_id
		{
			get
			{
				return this._genre_id;
			}
			set
			{
				if ((this._genre_id != value))
				{
					this._genre_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_id", DbType="Int")]
		public System.Nullable<int> sub_id
		{
			get
			{
				return this._sub_id;
			}
			set
			{
				if ((this._sub_id != value))
				{
					this._sub_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.game_publisher")]
	public partial class game_publisher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _game_id;
		
		private string _publisher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongame_idChanging(int value);
    partial void Ongame_idChanged();
    partial void OnpublisherChanging(string value);
    partial void OnpublisherChanged();
    #endregion
		
		public game_publisher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int game_id
		{
			get
			{
				return this._game_id;
			}
			set
			{
				if ((this._game_id != value))
				{
					this.Ongame_idChanging(value);
					this.SendPropertyChanging();
					this._game_id = value;
					this.SendPropertyChanged("game_id");
					this.Ongame_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publisher", DbType="NVarChar(500)")]
		public string publisher
		{
			get
			{
				return this._publisher;
			}
			set
			{
				if ((this._publisher != value))
				{
					this.OnpublisherChanging(value);
					this.SendPropertyChanging();
					this._publisher = value;
					this.SendPropertyChanged("publisher");
					this.OnpublisherChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.game_version_categories")]
	public partial class game_version_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private byte _category_id;
		
		private int _game_version_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncategory_idChanging(byte value);
    partial void Oncategory_idChanged();
    partial void Ongame_version_idChanging(int value);
    partial void Ongame_version_idChanged();
    #endregion
		
		public game_version_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="TinyInt NOT NULL")]
		public byte category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_version_id", DbType="Int NOT NULL")]
		public int game_version_id
		{
			get
			{
				return this._game_version_id;
			}
			set
			{
				if ((this._game_version_id != value))
				{
					this.Ongame_version_idChanging(value);
					this.SendPropertyChanging();
					this._game_version_id = value;
					this.SendPropertyChanged("game_version_id");
					this.Ongame_version_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.game_version_contents")]
	public partial class game_version_content
	{
		
		private int _id;
		
		private System.Nullable<int> _content_id;
		
		private System.Nullable<int> _game_version_id;
		
		public game_version_content()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_id", DbType="Int")]
		public System.Nullable<int> content_id
		{
			get
			{
				return this._content_id;
			}
			set
			{
				if ((this._content_id != value))
				{
					this._content_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_version_id", DbType="Int")]
		public System.Nullable<int> game_version_id
		{
			get
			{
				return this._game_version_id;
			}
			set
			{
				if ((this._game_version_id != value))
				{
					this._game_version_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.game_versions")]
	public partial class game_version
	{
		
		private int _id;
		
		private System.Nullable<int> _game_id;
		
		private System.Nullable<int> _platform_id;
		
		private System.Nullable<int> _source_id;
		
		private System.Nullable<int> _result_id;
		
		private System.Nullable<int> _age_id;
		
		private System.Nullable<bool> _is_source_available;
		
		private string _quality;
		
		private System.Nullable<bool> _haveproblem;
		
		private string _problem;
		
		public game_version()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_id", DbType="Int")]
		public System.Nullable<int> game_id
		{
			get
			{
				return this._game_id;
			}
			set
			{
				if ((this._game_id != value))
				{
					this._game_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform_id", DbType="Int")]
		public System.Nullable<int> platform_id
		{
			get
			{
				return this._platform_id;
			}
			set
			{
				if ((this._platform_id != value))
				{
					this._platform_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_id", DbType="Int")]
		public System.Nullable<int> source_id
		{
			get
			{
				return this._source_id;
			}
			set
			{
				if ((this._source_id != value))
				{
					this._source_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_id", DbType="Int")]
		public System.Nullable<int> result_id
		{
			get
			{
				return this._result_id;
			}
			set
			{
				if ((this._result_id != value))
				{
					this._result_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_id", DbType="Int")]
		public System.Nullable<int> age_id
		{
			get
			{
				return this._age_id;
			}
			set
			{
				if ((this._age_id != value))
				{
					this._age_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_source_available", DbType="Bit")]
		public System.Nullable<bool> is_source_available
		{
			get
			{
				return this._is_source_available;
			}
			set
			{
				if ((this._is_source_available != value))
				{
					this._is_source_available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quality", DbType="NVarChar(15)")]
		public string quality
		{
			get
			{
				return this._quality;
			}
			set
			{
				if ((this._quality != value))
				{
					this._quality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haveproblem", DbType="Bit")]
		public System.Nullable<bool> haveproblem
		{
			get
			{
				return this._haveproblem;
			}
			set
			{
				if ((this._haveproblem != value))
				{
					this._haveproblem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problem", DbType="NVarChar(MAX)")]
		public string problem
		{
			get
			{
				return this._problem;
			}
			set
			{
				if ((this._problem != value))
				{
					this._problem = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.games")]
	public partial class game
	{
		
		private int _id;
		
		private string _name;
		
		private string _developer;
		
		private System.Nullable<long> _publish_date;
		
		private string _name2;
		
		private string _icon;
		
		private string _esra_summary;
		
		public game()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_developer", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string developer
		{
			get
			{
				return this._developer;
			}
			set
			{
				if ((this._developer != value))
				{
					this._developer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_date", DbType="BigInt")]
		public System.Nullable<long> publish_date
		{
			get
			{
				return this._publish_date;
			}
			set
			{
				if ((this._publish_date != value))
				{
					this._publish_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name2", DbType="NVarChar(MAX)")]
		public string name2
		{
			get
			{
				return this._name2;
			}
			set
			{
				if ((this._name2 != value))
				{
					this._name2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="NVarChar(MAX)")]
		public string icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				if ((this._icon != value))
				{
					this._icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_summary", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string esra_summary
		{
			get
			{
				return this._esra_summary;
			}
			set
			{
				if ((this._esra_summary != value))
				{
					this._esra_summary = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.games_introduction")]
	public partial class games_introduction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _publisher;
		
		private System.Nullable<long> _publish_date;
		
		private System.Nullable<int> _source_id;
		
		private System.Nullable<byte> _reviewers_score;
		
		private System.Nullable<byte> _esra_grade;
		
		private System.Nullable<byte> _esra_skill;
		
		private System.Nullable<byte> _esra_violence;
		
		private System.Nullable<byte> _esra_fear;
		
		private System.Nullable<byte> _esra_drugs;
		
		private System.Nullable<byte> _esra_anomalies;
		
		private System.Nullable<byte> _esra_despair;
		
		private string _intro_title;
		
		private string _intro_gameplay;
		
		private string _intro_parents;
		
		private string _image_path;
		
		private long _create_date;
		
		private System.Nullable<int> _star1;
		
		private System.Nullable<int> _star2;
		
		private System.Nullable<int> _star3;
		
		private System.Nullable<int> _star4;
		
		private System.Nullable<int> _star5;
		
		private System.Nullable<byte> _esra_english;
		
		private System.Nullable<int> _album_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpublisherChanging(string value);
    partial void OnpublisherChanged();
    partial void Onpublish_dateChanging(System.Nullable<long> value);
    partial void Onpublish_dateChanged();
    partial void Onsource_idChanging(System.Nullable<int> value);
    partial void Onsource_idChanged();
    partial void Onreviewers_scoreChanging(System.Nullable<byte> value);
    partial void Onreviewers_scoreChanged();
    partial void Onesra_gradeChanging(System.Nullable<byte> value);
    partial void Onesra_gradeChanged();
    partial void Onesra_skillChanging(System.Nullable<byte> value);
    partial void Onesra_skillChanged();
    partial void Onesra_violenceChanging(System.Nullable<byte> value);
    partial void Onesra_violenceChanged();
    partial void Onesra_fearChanging(System.Nullable<byte> value);
    partial void Onesra_fearChanged();
    partial void Onesra_drugsChanging(System.Nullable<byte> value);
    partial void Onesra_drugsChanged();
    partial void Onesra_anomaliesChanging(System.Nullable<byte> value);
    partial void Onesra_anomaliesChanged();
    partial void Onesra_despairChanging(System.Nullable<byte> value);
    partial void Onesra_despairChanged();
    partial void Onintro_titleChanging(string value);
    partial void Onintro_titleChanged();
    partial void Onintro_gameplayChanging(string value);
    partial void Onintro_gameplayChanged();
    partial void Onintro_parentsChanging(string value);
    partial void Onintro_parentsChanged();
    partial void Onimage_pathChanging(string value);
    partial void Onimage_pathChanged();
    partial void Oncreate_dateChanging(long value);
    partial void Oncreate_dateChanged();
    partial void Onstar1Changing(System.Nullable<int> value);
    partial void Onstar1Changed();
    partial void Onstar2Changing(System.Nullable<int> value);
    partial void Onstar2Changed();
    partial void Onstar3Changing(System.Nullable<int> value);
    partial void Onstar3Changed();
    partial void Onstar4Changing(System.Nullable<int> value);
    partial void Onstar4Changed();
    partial void Onstar5Changing(System.Nullable<int> value);
    partial void Onstar5Changed();
    partial void Onesra_englishChanging(System.Nullable<byte> value);
    partial void Onesra_englishChanged();
    partial void Onalbum_idChanging(System.Nullable<int> value);
    partial void Onalbum_idChanged();
    #endregion
		
		public games_introduction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publisher", DbType="NVarChar(100)")]
		public string publisher
		{
			get
			{
				return this._publisher;
			}
			set
			{
				if ((this._publisher != value))
				{
					this.OnpublisherChanging(value);
					this.SendPropertyChanging();
					this._publisher = value;
					this.SendPropertyChanged("publisher");
					this.OnpublisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_date", DbType="BigInt")]
		public System.Nullable<long> publish_date
		{
			get
			{
				return this._publish_date;
			}
			set
			{
				if ((this._publish_date != value))
				{
					this.Onpublish_dateChanging(value);
					this.SendPropertyChanging();
					this._publish_date = value;
					this.SendPropertyChanged("publish_date");
					this.Onpublish_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_id", DbType="Int")]
		public System.Nullable<int> source_id
		{
			get
			{
				return this._source_id;
			}
			set
			{
				if ((this._source_id != value))
				{
					this.Onsource_idChanging(value);
					this.SendPropertyChanging();
					this._source_id = value;
					this.SendPropertyChanged("source_id");
					this.Onsource_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reviewers_score", DbType="TinyInt")]
		public System.Nullable<byte> reviewers_score
		{
			get
			{
				return this._reviewers_score;
			}
			set
			{
				if ((this._reviewers_score != value))
				{
					this.Onreviewers_scoreChanging(value);
					this.SendPropertyChanging();
					this._reviewers_score = value;
					this.SendPropertyChanged("reviewers_score");
					this.Onreviewers_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_grade", DbType="TinyInt")]
		public System.Nullable<byte> esra_grade
		{
			get
			{
				return this._esra_grade;
			}
			set
			{
				if ((this._esra_grade != value))
				{
					this.Onesra_gradeChanging(value);
					this.SendPropertyChanging();
					this._esra_grade = value;
					this.SendPropertyChanged("esra_grade");
					this.Onesra_gradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_skill", DbType="TinyInt")]
		public System.Nullable<byte> esra_skill
		{
			get
			{
				return this._esra_skill;
			}
			set
			{
				if ((this._esra_skill != value))
				{
					this.Onesra_skillChanging(value);
					this.SendPropertyChanging();
					this._esra_skill = value;
					this.SendPropertyChanged("esra_skill");
					this.Onesra_skillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_violence", DbType="TinyInt")]
		public System.Nullable<byte> esra_violence
		{
			get
			{
				return this._esra_violence;
			}
			set
			{
				if ((this._esra_violence != value))
				{
					this.Onesra_violenceChanging(value);
					this.SendPropertyChanging();
					this._esra_violence = value;
					this.SendPropertyChanged("esra_violence");
					this.Onesra_violenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_fear", DbType="TinyInt")]
		public System.Nullable<byte> esra_fear
		{
			get
			{
				return this._esra_fear;
			}
			set
			{
				if ((this._esra_fear != value))
				{
					this.Onesra_fearChanging(value);
					this.SendPropertyChanging();
					this._esra_fear = value;
					this.SendPropertyChanged("esra_fear");
					this.Onesra_fearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_drugs", DbType="TinyInt")]
		public System.Nullable<byte> esra_drugs
		{
			get
			{
				return this._esra_drugs;
			}
			set
			{
				if ((this._esra_drugs != value))
				{
					this.Onesra_drugsChanging(value);
					this.SendPropertyChanging();
					this._esra_drugs = value;
					this.SendPropertyChanged("esra_drugs");
					this.Onesra_drugsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_anomalies", DbType="TinyInt")]
		public System.Nullable<byte> esra_anomalies
		{
			get
			{
				return this._esra_anomalies;
			}
			set
			{
				if ((this._esra_anomalies != value))
				{
					this.Onesra_anomaliesChanging(value);
					this.SendPropertyChanging();
					this._esra_anomalies = value;
					this.SendPropertyChanged("esra_anomalies");
					this.Onesra_anomaliesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_despair", DbType="TinyInt")]
		public System.Nullable<byte> esra_despair
		{
			get
			{
				return this._esra_despair;
			}
			set
			{
				if ((this._esra_despair != value))
				{
					this.Onesra_despairChanging(value);
					this.SendPropertyChanging();
					this._esra_despair = value;
					this.SendPropertyChanged("esra_despair");
					this.Onesra_despairChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intro_title", DbType="NVarChar(200)")]
		public string intro_title
		{
			get
			{
				return this._intro_title;
			}
			set
			{
				if ((this._intro_title != value))
				{
					this.Onintro_titleChanging(value);
					this.SendPropertyChanging();
					this._intro_title = value;
					this.SendPropertyChanged("intro_title");
					this.Onintro_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intro_gameplay", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string intro_gameplay
		{
			get
			{
				return this._intro_gameplay;
			}
			set
			{
				if ((this._intro_gameplay != value))
				{
					this.Onintro_gameplayChanging(value);
					this.SendPropertyChanging();
					this._intro_gameplay = value;
					this.SendPropertyChanged("intro_gameplay");
					this.Onintro_gameplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intro_parents", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string intro_parents
		{
			get
			{
				return this._intro_parents;
			}
			set
			{
				if ((this._intro_parents != value))
				{
					this.Onintro_parentsChanging(value);
					this.SendPropertyChanging();
					this._intro_parents = value;
					this.SendPropertyChanged("intro_parents");
					this.Onintro_parentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_path", DbType="NVarChar(500)")]
		public string image_path
		{
			get
			{
				return this._image_path;
			}
			set
			{
				if ((this._image_path != value))
				{
					this.Onimage_pathChanging(value);
					this.SendPropertyChanging();
					this._image_path = value;
					this.SendPropertyChanged("image_path");
					this.Onimage_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="BigInt NOT NULL")]
		public long create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star1", DbType="Int")]
		public System.Nullable<int> star1
		{
			get
			{
				return this._star1;
			}
			set
			{
				if ((this._star1 != value))
				{
					this.Onstar1Changing(value);
					this.SendPropertyChanging();
					this._star1 = value;
					this.SendPropertyChanged("star1");
					this.Onstar1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star2", DbType="Int")]
		public System.Nullable<int> star2
		{
			get
			{
				return this._star2;
			}
			set
			{
				if ((this._star2 != value))
				{
					this.Onstar2Changing(value);
					this.SendPropertyChanging();
					this._star2 = value;
					this.SendPropertyChanged("star2");
					this.Onstar2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star3", DbType="Int")]
		public System.Nullable<int> star3
		{
			get
			{
				return this._star3;
			}
			set
			{
				if ((this._star3 != value))
				{
					this.Onstar3Changing(value);
					this.SendPropertyChanging();
					this._star3 = value;
					this.SendPropertyChanged("star3");
					this.Onstar3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star4", DbType="Int")]
		public System.Nullable<int> star4
		{
			get
			{
				return this._star4;
			}
			set
			{
				if ((this._star4 != value))
				{
					this.Onstar4Changing(value);
					this.SendPropertyChanging();
					this._star4 = value;
					this.SendPropertyChanged("star4");
					this.Onstar4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star5", DbType="Int")]
		public System.Nullable<int> star5
		{
			get
			{
				return this._star5;
			}
			set
			{
				if ((this._star5 != value))
				{
					this.Onstar5Changing(value);
					this.SendPropertyChanging();
					this._star5 = value;
					this.SendPropertyChanged("star5");
					this.Onstar5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esra_english", DbType="TinyInt")]
		public System.Nullable<byte> esra_english
		{
			get
			{
				return this._esra_english;
			}
			set
			{
				if ((this._esra_english != value))
				{
					this.Onesra_englishChanging(value);
					this.SendPropertyChanging();
					this._esra_english = value;
					this.SendPropertyChanged("esra_english");
					this.Onesra_englishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_id", DbType="Int")]
		public System.Nullable<int> album_id
		{
			get
			{
				return this._album_id;
			}
			set
			{
				if ((this._album_id != value))
				{
					this.Onalbum_idChanging(value);
					this.SendPropertyChanging();
					this._album_id = value;
					this.SendPropertyChanged("album_id");
					this.Onalbum_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.games_introduction_genres")]
	public partial class games_introduction_genre
	{
		
		private int _game_id;
		
		private int _genre_id;
		
		private System.Nullable<int> _subgenre_id;
		
		public games_introduction_genre()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_id", DbType="Int NOT NULL")]
		public int game_id
		{
			get
			{
				return this._game_id;
			}
			set
			{
				if ((this._game_id != value))
				{
					this._game_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre_id", DbType="Int NOT NULL")]
		public int genre_id
		{
			get
			{
				return this._genre_id;
			}
			set
			{
				if ((this._genre_id != value))
				{
					this._genre_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subgenre_id", DbType="Int")]
		public System.Nullable<int> subgenre_id
		{
			get
			{
				return this._subgenre_id;
			}
			set
			{
				if ((this._subgenre_id != value))
				{
					this._subgenre_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.games_introduction_platforms")]
	public partial class games_introduction_platform
	{
		
		private int _game_id;
		
		private int _platform_id;
		
		public games_introduction_platform()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_id", DbType="Int NOT NULL")]
		public int game_id
		{
			get
			{
				return this._game_id;
			}
			set
			{
				if ((this._game_id != value))
				{
					this._game_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform_id", DbType="Int NOT NULL")]
		public int platform_id
		{
			get
			{
				return this._platform_id;
			}
			set
			{
				if ((this._platform_id != value))
				{
					this._platform_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.genres")]
	public partial class genre
	{
		
		private int _id;
		
		private string _title;
		
		public genre()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.isactive")]
	public partial class isactive
	{
		
		private string _state;
		
		public isactive()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.littlenews")]
	public partial class littlenew
	{
		
		private int _id;
		
		private string _news;
		
		private System.Nullable<long> _date;
		
		public littlenew()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string news
		{
			get
			{
				return this._news;
			}
			set
			{
				if ((this._news != value))
				{
					this._news = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="BigInt")]
		public System.Nullable<long> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.logins")]
	public partial class login
	{
		
		private long _time;
		
		private string _username;
		
		private string _used_pass;
		
		private string _userlogon;
		
		private string _host_address;
		
		private string _host_name;
		
		private string _user_agent;
		
		private string _url;
		
		private string _login1;
		
		public login()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="BigInt NOT NULL")]
		public long time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_used_pass", DbType="NVarChar(100)")]
		public string used_pass
		{
			get
			{
				return this._used_pass;
			}
			set
			{
				if ((this._used_pass != value))
				{
					this._used_pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userlogon", DbType="NVarChar(100)")]
		public string userlogon
		{
			get
			{
				return this._userlogon;
			}
			set
			{
				if ((this._userlogon != value))
				{
					this._userlogon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host_address", DbType="NVarChar(100)")]
		public string host_address
		{
			get
			{
				return this._host_address;
			}
			set
			{
				if ((this._host_address != value))
				{
					this._host_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host_name", DbType="NVarChar(100)")]
		public string host_name
		{
			get
			{
				return this._host_name;
			}
			set
			{
				if ((this._host_name != value))
				{
					this._host_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_agent", DbType="NVarChar(200)")]
		public string user_agent
		{
			get
			{
				return this._user_agent;
			}
			set
			{
				if ((this._user_agent != value))
				{
					this._user_agent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="login", Storage="_login1", DbType="NVarChar(50)")]
		public string login1
		{
			get
			{
				return this._login1;
			}
			set
			{
				if ((this._login1 != value))
				{
					this._login1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Module_user")]
	public partial class Module_user
	{
		
		private int _module_id;
		
		private string _username;
		
		public Module_user()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="Int NOT NULL")]
		public int module_id
		{
			get
			{
				return this._module_id;
			}
			set
			{
				if ((this._module_id != value))
				{
					this._module_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modules")]
	public partial class Module
	{
		
		private int _id;
		
		private string _name;
		
		private string _class;
		
		private string _levelofaccess;
		
		private string _type;
		
		private string _url;
		
		private string _title;
		
		private string _ishidden;
		
		private System.Nullable<bool> _isroot;
		
		private System.Nullable<int> _root_id;
		
		private string _menuIcon;
		
		private System.Nullable<long> _cdate;
		
		public Module()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="NVarChar(50)")]
		public string @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this._class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_levelofaccess", DbType="NVarChar(50)")]
		public string levelofaccess
		{
			get
			{
				return this._levelofaccess;
			}
			set
			{
				if ((this._levelofaccess != value))
				{
					this._levelofaccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ishidden", DbType="NChar(10)")]
		public string ishidden
		{
			get
			{
				return this._ishidden;
			}
			set
			{
				if ((this._ishidden != value))
				{
					this._ishidden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isroot", DbType="Bit")]
		public System.Nullable<bool> isroot
		{
			get
			{
				return this._isroot;
			}
			set
			{
				if ((this._isroot != value))
				{
					this._isroot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_root_id", DbType="Int")]
		public System.Nullable<int> root_id
		{
			get
			{
				return this._root_id;
			}
			set
			{
				if ((this._root_id != value))
				{
					this._root_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menuIcon", DbType="NVarChar(MAX)")]
		public string menuIcon
		{
			get
			{
				return this._menuIcon;
			}
			set
			{
				if ((this._menuIcon != value))
				{
					this._menuIcon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdate", DbType="BigInt")]
		public System.Nullable<long> cdate
		{
			get
			{
				return this._cdate;
			}
			set
			{
				if ((this._cdate != value))
				{
					this._cdate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.payamha")]
	public partial class payamha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<long> _date;
		
		private string _payam;
		
		private string _class;
		
		private string _username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<long> value);
    partial void OndateChanged();
    partial void OnpayamChanging(string value);
    partial void OnpayamChanged();
    partial void OnclassChanging(string value);
    partial void OnclassChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public payamha()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="BigInt")]
		public System.Nullable<long> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payam", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string payam
		{
			get
			{
				return this._payam;
			}
			set
			{
				if ((this._payam != value))
				{
					this.OnpayamChanging(value);
					this.SendPropertyChanging();
					this._payam = value;
					this.SendPropertyChanged("payam");
					this.OnpayamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="NVarChar(50)")]
		public string @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this.OnclassChanging(value);
					this.SendPropertyChanging();
					this._class = value;
					this.SendPropertyChanged("@class");
					this.OnclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.platforms")]
	public partial class platform
	{
		
		private int _id;
		
		private string _title;
		
		public platform()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.publisher_user")]
	public partial class publisher_user
	{
		
		private string _username;
		
		private int _publisher_id;
		
		public publisher_user()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publisher_id", DbType="Int NOT NULL")]
		public int publisher_id
		{
			get
			{
				return this._publisher_id;
			}
			set
			{
				if ((this._publisher_id != value))
				{
					this._publisher_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.publishers")]
	public partial class publisher
	{
		
		private int _id;
		
		private string _name;
		
		private string _company_register_code;
		
		private string _address;
		
		private string _tel;
		
		private string _email;
		
		private string _postal_code;
		
		private string _total_copon;
		
		private string _total_hologram;
		
		private string _isActive;
		
		public publisher()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_register_code", DbType="NVarChar(50)")]
		public string company_register_code
		{
			get
			{
				return this._company_register_code;
			}
			set
			{
				if ((this._company_register_code != value))
				{
					this._company_register_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this._tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="NVarChar(50)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this._postal_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_copon", DbType="NVarChar(50)")]
		public string total_copon
		{
			get
			{
				return this._total_copon;
			}
			set
			{
				if ((this._total_copon != value))
				{
					this._total_copon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_hologram", DbType="NVarChar(50)")]
		public string total_hologram
		{
			get
			{
				return this._total_hologram;
			}
			set
			{
				if ((this._total_hologram != value))
				{
					this._total_hologram = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="NVarChar(50)")]
		public string isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this._isActive = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.results")]
	public partial class result
	{
		
		private int _id;
		
		private string _title;
		
		public result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sources")]
	public partial class source
	{
		
		private int _id;
		
		private string _title;
		
		public source()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sub_genres")]
	public partial class sub_genre
	{
		
		private int _id;
		
		private string _title;
		
		private System.Nullable<int> _genre_id;
		
		public sub_genre()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre_id", DbType="Int")]
		public System.Nullable<int> genre_id
		{
			get
			{
				return this._genre_id;
			}
			set
			{
				if ((this._genre_id != value))
				{
					this._genre_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
